synapse_admin:
    resource: '@SynapseAdmin/src/Admin/Controller/'
    type: attribute

synapse_admin_v2:
    resource: '@SynapseAdmin/src/AdminV2/Controller/'
    type: attribute

synapse_api:
    resource: '@SynapseChat/src/Core/Controller/Api/'
    type: attribute
